dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
    solc:
      remappings:
        - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
        - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  development:
    verify: False
  SolidStateTest:
    private_key: ${PRIVATE_KEY_LOCAL}
    verify: False
    cmd_settings:
      chain_id: 1337 
  kovan:
    private_key: ${PRIVATE_KEY_KOVAN}
    verify: True
    eth_usd_price_feed: '0x9326BFA02ADD2366b30bacB125260Af641031331'